FROM golang:alpine AS builder
MAINTAINER Ty Sarna <ty@sarna.org>

RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/mypackage/myapp/
COPY . .

RUN go get -d -v

RUN GOOS=linux GOARCH=arm64 go build -ldflags="-w -s" -o /zoneupdated

FROM scratch

COPY --from=builder /zoneupdated /zoneupdated

ENTRYPOINT ["/zoneupdated"]
