#!/bin/bash

cd .. # Not sure why PWD is the docker dir and not the specified build context?

for ARCH in ${BUILD_ARCHES:=amd64 arm64}; do
  echo docker build --platform=$ARCH --build-arg goarch=${ARCH} -f $DOCKERFILE_PATH -t $IMAGE_NAME-$ARCH .
done
